"""create agent_roles agent_skills agent_metrics tables

Revision ID: 9a7b3c1d
Revises: 64d21646b23e
Create Date: 2026-04-21 22:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a7b3c1d'
down_revision: Union[str, None] = '64d21646b23e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_roles',
    sa.Column('id', sa.TEXT(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('system_prompt_template', sa.Text(), nullable=True),
    sa.Column('default_config', sa.Text(), nullable=True),
    sa.Column('org_id', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_skills',
    sa.Column('id', sa.TEXT(), nullable=False),
    sa.Column('agent_id', sa.TEXT(), nullable=False),
    sa.Column('skill_name', sa.String(length=128), nullable=False),
    sa.Column('skill_config', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_metrics',
    sa.Column('id', sa.TEXT(), nullable=False),
    sa.Column('agent_id', sa.TEXT(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('tasks_completed', sa.Integer(), nullable=True),
    sa.Column('tasks_failed', sa.Integer(), nullable=True),
    sa.Column('avg_response_time_ms', sa.Integer(), nullable=True),
    sa.Column('token_usage', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agent_metrics')
    op.drop_table('agent_skills')
    op.drop_table('agent_roles')
    # ### end Alembic commands ###